language: node_js

node_js:
  - "6.10"
  - "lts/*"

cache:
  directories:
    - "node_modules"

script:
  - npm run build
  - npm run test

deploy:
  - provider: npm
    skip_cleanup: true
    email: "web-tech+npm@20minutes.fr"
    api_key:
      secure: 43l35EhDyCAmZ2jgDBx5NxAY9fk/narKfw0xdAkwsEiGX9v8KYPP9+iVeewgU+iYZeVscy42u+xPOOL4gXGOtnDerZJ8SZyzyAMagltp3goh8gk5M2q82yK6u4g3GsSSnRs/0+79zedTYBFZsXwlqZt9WDThb9hRDJe72r3CUtRIuWEViEZbDoogbtkZ6/4NJbEZ/clnj7QYqkjsFrmX04eglqY41hq1Q8lbBIKKkHxAtrDQAyRyNEx+zfpmTreIIJI+mCO9YZFWZqeK40uYy55km7zsbToi9niWpfwycrJzS4iU7GIDCNGTQ2s56Lio5to3Z9uquISZAHvRhNLQal6d4jKVHkaaKM4HmEH75hz30QkdFbe9jABU0jgsV33LYL7wICC4Mc2lYSzwI1POazGrccWKf9Kc6Kszg6pDWd8COsibMTCdr9TKEPFN+O6RSCmBBcMrh0+wpc0Ug1fqycvX/zG0HbBFpwJxCFcFebyzgjcrnF10FYkMsB0Iz+0zgDHe9HtwPJIm1Uxk4GhQujYgNwuqeo+bPEOV++U4DGtzh75x58oQ7RNXi8NQSjOVdKsZws9Nkgo/0g+yesmL8zeGA5DRxF4dHuqJAnPA+cX4q2F3l2bHsXrUhUOekqQJznX5XtUGyDB9FJJGmfE6tKNZZwjLrFon9bAf+N4JQAg=
    on:
      tags: true
